{{- if .Values.userResearch.enabled and .Values.userResearch.renewal }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ent-cloud-ut
spec:
  selector:
    matchLabels:
      app: ent-cloud-ut
  template:
    metadata:
      labels:
        app: ent-cloud-ut
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- .Values.imagePullSecrets | toYaml | nindent 8 }}
      {{- else if .Values.imageCredentials }}
      imagePullSecrets:
      - name: protopie-private-registry
      {{- end }}
      containers:
        - name: ent-cloud-ut
          image: "{{ .Values.image.cloud.userResearch.repository }}:{{ .Values.image.cloud.userResearch.renwalTag }}"
          imagePullPolicy: {{ .Values.image.cloud.userResearch.pullPolicy }}
          env:
            - name: API_URL
              value: "http://ent-cloud-api-svc.{{ .Release.Namespace }}.svc.cluster.local"
          ports:
            - containerPort: 4444
            - containerPort: 4445
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "1"
              memory: "4Gi"
      volumes:
        - name: logs
          hostPath:
            path: /home/ec2-user/logs
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: ent-cloud-ut-svc
spec:
  selector:
    app: ent-cloud-ut
  ports:
    - name: cloud-ut-api
      port: 80
      targetPort: 4444
    - name: cloud-ut-socket
      port: 8081
      targetPort: 4445
{{- end }}
