apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-cloud-web
spec:
  selector:
    matchLabels:
      app: ent-cloud-web
  replicas: {{ .Values.cloud.web.replicas }}
  template:
    metadata:
      labels:
        app: ent-cloud-web
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- .Values.imagePullSecrets | toYaml | nindent 8 }}
      {{- else if .Values.imageCredentials }}
      imagePullSecrets:
      - name: protopie-private-registry
      {{- end }}
      containers:
        - name: ent-cloud-web
          image: "{{ .Values.image.cloud.web.repository }}:{{ .Values.image.cloud.web.tag }}"
          imagePullPolicy: {{ .Values.image.cloud.web.pullPolicy }}
          ports:
            - containerPort: 3000
