ingress:
  enabled: true
  # Example host
  host: onpremises.protopie.works
  annotations:
    # Example for AWS EKS. Please modify the annotations to your cloud provider.
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-min-version: TLSV12
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:310455165573:certificate/f4e3633c-f6b9-47ae-a265-61bc2f7e66cc
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-2019-08 # ELBSecurityPolicy-2016-08
    external-dns.alpha.kubernetes.io/hostname: onpremises.protopie.works

image:
  cloud:
    api:
      pullPolicy: IfNotPresent
      repository: protopie/enterprise-onpremises
      tag: api-12.0.1
    web:
      pullPolicy: IfNotPresent
      repository: protopie/enterprise-onpremises
      tag: web-11.0.5

cloud:
  api:
    replicas: 2
  web:
    replicas: 2
  # Europ/Berlin 5 AM - UTC 3 AM - 0 3 * * *
  # America/NewYork 6 AM - UTC 10 AM - 0 10 * * *
  # America/California 3 AM - UTC 10 AM - 0 10 * * *
  # Asia/Mumbai 5 AM - UTC 11:30 PM - 30 11 * * *
  # Asia/Seoul 5 AM - UTC 20 PM - 0 20 * * *
  cleanUpSchedule: "* 20 * * *"

nginx:
  replicas: 2

analytics:
  enabled: false # This feature is a closed alpha, there are no public images

userResearch:
  enabled: false # This feature is a closed alpha, there are no public images
